"""add blog_image_file to blogposts

Revision ID: 36894ad1de07
Revises: 9500279d7344
Create Date: 2026-07-09 11:43:38.626803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36894ad1de07'
down_revision: Union[str, Sequence[str], None] = '9500279d7344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('blog_image_file', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogposts', 'blog_image_file')
    # ### end Alembic commands ###
