"""initial schema

Revision ID: 661e46fa971e
Revises: 
Create Date: 2026-07-03 07:10:49.441287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '661e46fa971e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=220), nullable=False),
    sa.Column('image_file', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('blogposts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogposts_id'), 'blogposts', ['id'], unique=False)
    op.create_index(op.f('ix_blogposts_user_id'), 'blogposts', ['user_id'], unique=False)
    op.create_table('password_rest_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_rest_token_id'), 'password_rest_token', ['id'], unique=False)
    op.drop_index(op.f('ix_labbooks_id'), table_name='labbooks')
    op.drop_table('labbooks')
    op.drop_index(op.f('ix_bookusers_email'), table_name='bookusers')
    op.drop_index(op.f('ix_bookusers_hashed_password'), table_name='bookusers')
    op.drop_index(op.f('ix_bookusers_id'), table_name='bookusers')
    op.drop_index(op.f('ix_bookusers_username'), table_name='bookusers')
    op.drop_table('bookusers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookusers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bookusers_pkey'))
    )
    op.create_index(op.f('ix_bookusers_username'), 'bookusers', ['username'], unique=True)
    op.create_index(op.f('ix_bookusers_id'), 'bookusers', ['id'], unique=False)
    op.create_index(op.f('ix_bookusers_hashed_password'), 'bookusers', ['hashed_password'], unique=True)
    op.create_index(op.f('ix_bookusers_email'), 'bookusers', ['email'], unique=True)
    op.create_table('labbooks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('publish_date', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('labbooks_pkey'))
    )
    op.create_index(op.f('ix_labbooks_id'), 'labbooks', ['id'], unique=False)
    op.drop_index(op.f('ix_password_rest_token_id'), table_name='password_rest_token')
    op.drop_table('password_rest_token')
    op.drop_index(op.f('ix_blogposts_user_id'), table_name='blogposts')
    op.drop_index(op.f('ix_blogposts_id'), table_name='blogposts')
    op.drop_table('blogposts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
