services:
  backend:
    build:
      context: ./backend
    container_name: "fastapi-server"
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8080/api}
    container_name: "nextjs-blog-client"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
